services:
  garlictext:
    build: ./frontend
    depends_on:
      # - python_service
      - backend
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_PYTHON_SERVICE_URL=http://python_service:8000

  python_service:
    build: ./python_backend
    ports:
      - "8000:8000"
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

  
    
    
    

